.TH "CluedoBoardController.BoardCell" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CluedoBoardController.BoardCell
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2Int \fBgridPosition\fP"
.br
.ti -1c
.RI "Room \fBroom\fP"
.br
.ti -1c
.RI "bool \fBisRoomEntrance\fP"
.br
.ti -1c
.RI "Room \fBentranceLeadsTo\fP"
.br
.ti -1c
.RI "List< \fBBoardCell\fP > \fBneighbors\fP = new()"
.br
.ti -1c
.RI "GameObject \fBworldObject\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsInRoom\fP\fR [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
