.TH "CluedoBoardController.Player" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CluedoBoardController.Player
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBHasCard\fP (\fBCluedoCard\fP card)"
.br
.ti -1c
.RI "\fBCluedoCard\fP \fBRevealCardFor\fP (\fBCluedoCard\fP suspect, \fBCluedoCard\fP weapon, \fBCluedoCard\fP room)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBplayerName\fP"
.br
.ti -1c
.RI "Suspect \fBcharacter\fP"
.br
.ti -1c
.RI "List< \fBCluedoCard\fP > \fBhand\fP = new()"
.br
.ti -1c
.RI "\fBBoardCell\fP \fBcurrentCell\fP"
.br
.ti -1c
.RI "bool \fBisEliminated\fP"
.br
.ti -1c
.RI "bool \fBisHuman\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
