.TH "CluedoBoardData" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CluedoBoardData \- ScriptableObject that describes the Cluedo board layout\&. Create via: right-click in Project → Create → Cluedo → Board Data\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector3 \fBGridToWorld\fP (int x, int y)"
.br
.ti -1c
.RI "Vector2Int \fBWorldToGrid\fP (Vector3 world)"
.br
.ti -1c
.RI "\fBRoomDefinition\fP \fBGetRoom\fP (CluedoEnums\&.Room room)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBgridWidth\fP = 24"
.br
.ti -1c
.RI "int \fBgridHeight\fP = 25"
.br
.ti -1c
.RI "float \fBcellSize\fP = 1f"
.br
.ti -1c
.RI "Vector3 \fBboardOrigin\fP = new(\-12f, \-12\&.5f, 0f)"
.br
.ti -1c
.RI "List< \fBRoomDefinition\fP > \fBrooms\fP = new()"
.br
.ti -1c
.RI "List< Vector2Int > \fBblockedCells\fP = new()"
.br
.ti -1c
.RI "List< \fBSuspectStart\fP > \fBstartPositions\fP = new()"
.br
.in -1c
.SH "Detailed Description"
.PP 
ScriptableObject that describes the Cluedo board layout\&. Create via: right-click in Project → Create → Cluedo → Board Data\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
