.TH "Deck" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Deck \- Class \fR\fBDeck\fP\fP represents a deck of cards used in the game\&. The deck supports adding cards, removing them, and shuffling the deck\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeck\fP ()"
.br
.RI "Creates a new instance of the \fR \fBDeck\fP \fP\&. "
.ti -1c
.RI "void \fBAddCard\fP (\fBCard\fP newCard)"
.br
.RI "Adds a new \fR\fBCard\fP\fP to the deck\&. "
.ti -1c
.RI "void \fBShuffle\fP ()"
.br
.RI "Randomises the order of the cards in the deck using the Fisher-Yates shuffle\&. "
.ti -1c
.RI "\fBCard\fP \fBDrawCard\fP ()"
.br
.RI "Draws the top card from the deck\&. Where top is index 0\&. "
.ti -1c
.RI "int \fBCount\fP ()"
.br
.RI "Gets the number of cards currently in the deck\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBDeck\fP\fP represents a deck of cards used in the game\&. The deck supports adding cards, removing them, and shuffling the deck\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Deck\&.AddCard (\fBCard\fP newCard)"

.PP
Adds a new \fR\fBCard\fP\fP to the deck\&. 
.PP
\fBParameters\fP
.RS 4
\fInewCard\fP The new \fR\fBCard\fP\fP to be added\&. 
.RE
.PP

.SS "int Deck\&.Count ()"

.PP
Gets the number of cards currently in the deck\&. 
.PP
\fBReturns\fP
.RS 4
An \fRint\fP representing the number of cards in the deck\&. 
.RE
.PP

.SS "\fBCard\fP Deck\&.DrawCard ()"

.PP
Draws the top card from the deck\&. Where top is index 0\&. 
.PP
\fBReturns\fP
.RS 4
The \fR\fBCard\fP\fP drawn from the deck, or null if the deck is empty\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
