.TH "DetectiveCardEntry" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DetectiveCardEntry \- Represents a single card in the detective sheet (e\&.g\&. Ms Scarlett) The sheet UI has fixed number of player columns 6 rest columns will be inactive\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDetectiveCardEntry\fP (string cardName, int columnCount, int activePlayerCount)"
.br
.RI "Creates a new entry\&. columnCount should mathc the number of button per row in the UI activePlayercount is how many of those columns are real players (Ai and human) this game\&. "
.ti -1c
.RI "\fBDetectiveCardEntry\fP (string cardName)"
.br
.RI "Backwards compatible constructor: assumes a single active column\&. Prefer the (cardName, columnCount, activePlayerCount) form\&. "
.ti -1c
.RI "string \fBGetCardName\fP ()"
.br
.RI "Returns the name of the card\&. "
.ti -1c
.RI "int \fBGetColumnCount\fP ()"
.br
.RI "Total number of UI columns this entry tracks\&. "
.ti -1c
.RI "bool \fBIsColumnActive\fP (int playerIndex)"
.br
.RI "True if this column corresponds to a real player\&. "
.ti -1c
.RI "bool \fBShouldDisplayCross\fP (int playerIndex)"
.br
.RI "True if this column should be displayed by the UI Includes inactive columns\&. (so empty seats are x out) and active columns that have been auto/manual crossed out\&. "
.ti -1c
.RI "bool \fBIsCrossedOut\fP (int playerIndex)"
.br
.RI "True if this column is meaningfully crossed out for deduction purposes Inactive columns return false: they aren't real information\&. "
.ti -1c
.RI "bool \fBIsAutoCrossedOut\fP (int playerIndex)"
.br
.RI "Checks if the card been Auto crossed out\&. "
.ti -1c
.RI "bool \fBIsManualCrossedOut\fP (int playerIndex)"
.br
.RI "Returns if the card is manually crossed out\&. "
.ti -1c
.RI "void \fBMarkAuto\fP (int playerIndex)"
.br
.RI "System marks this column crossed inactive columns are not included\&. "
.ti -1c
.RI "void \fBMarkNotHeldBy\fP (int playerIndex)"
.br
.RI "Records that this player is know not to hold this card Used when a player fails to disprove a suggestion containing this card Different from MarkAuto: auto cross means "I saw them hold it", not held means "I deduced they don't have it"\&. "
.ti -1c
.RI "bool \fBIsKnownNotHeldBy\fP (int playerIndex)"
.br
.RI "True if we know this player does NOT hold this card\&. "
.ti -1c
.RI "void \fBMarkManual\fP (int playerIndex)"
.br
.RI "Marks the card as manually crossed out by the player inactive columns are not included\&. "
.ti -1c
.RI "void \fBUndoManual\fP (int playerIndex)"
.br
.RI "Human player un-ticks the cross button\&. "
.ti -1c
.RI "bool \fBIsAutoCrossedOutAnywhere\fP ()"
.br
.RI "True if a card been automatically crossed out\&. "
.ti -1c
.RI "bool \fBIsCrossedOutAnywhere\fP ()"
.br
.RI "True if any active column (auto or manual) is crossed\&. "
.ti -1c
.RI "bool \fBIsDefinitelyInEnvelope\fP ()"
.br
.ti -1c
.RI "bool \fBIsCrossedOut\fP ()"
.br
.ti -1c
.RI "bool \fBIsAutoCrossedOut\fP ()"
.br
.ti -1c
.RI "bool \fBIsManualCrossedOut\fP ()"
.br
.ti -1c
.RI "void \fBMarkAuto\fP ()"
.br
.ti -1c
.RI "void \fBMarkManual\fP ()"
.br
.ti -1c
.RI "void \fBUndoManual\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a single card in the detective sheet (e\&.g\&. Ms Scarlett) The sheet UI has fixed number of player columns 6 rest columns will be inactive\&. 

For each column this entry tracks three things: active: is there player in this col autoCrossedOut: the game auto marked this card manualCrossedOut: the human player ticked the cross button 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DetectiveCardEntry\&.DetectiveCardEntry (string cardName, int columnCount, int activePlayerCount)"

.PP
Creates a new entry\&. columnCount should mathc the number of button per row in the UI activePlayercount is how many of those columns are real players (Ai and human) this game\&. 
.PP
\fBParameters\fP
.RS 4
\fIcardName\fP Name of the card
.br
\fIcolumnCount\fP Totla UI Colums
.br
\fIactivePlayerCount\fP Real players this game
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool DetectiveCardEntry\&.IsAutoCrossedOut (int playerIndex)"

.PP
Checks if the card been Auto crossed out\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP postion
.RE
.PP
\fBReturns\fP
.RS 4
reutrns true if auto crossed out
.RE
.PP

.SS "bool DetectiveCardEntry\&.IsAutoCrossedOutAnywhere ()"

.PP
True if a card been automatically crossed out\&. 
.PP
\fBReturns\fP
.RS 4
Return true if card been crossed out automatically
.RE
.PP

.SS "bool DetectiveCardEntry\&.IsColumnActive (int playerIndex)"

.PP
True if this column corresponds to a real player\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP of postion
.RE
.PP
\fBReturns\fP
.RS 4
True if the corresponds to a real player
.RE
.PP

.SS "bool DetectiveCardEntry\&.IsCrossedOut (int playerIndex)"

.PP
True if this column is meaningfully crossed out for deduction purposes Inactive columns return false: they aren't real information\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP Postion of player
.RE
.PP
\fBReturns\fP
.RS 4
Returns true if column crossed out
.RE
.PP

.SS "bool DetectiveCardEntry\&.IsKnownNotHeldBy (int playerIndex)"

.PP
True if we know this player does NOT hold this card\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP Index postion
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool DetectiveCardEntry\&.IsManualCrossedOut (int playerIndex)"

.PP
Returns if the card is manually crossed out\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP postion
.RE
.PP
\fBReturns\fP
.RS 4
True if manually crossed out
.RE
.PP

.SS "void DetectiveCardEntry\&.MarkNotHeldBy (int playerIndex)"

.PP
Records that this player is know not to hold this card Used when a player fails to disprove a suggestion containing this card Different from MarkAuto: auto cross means "I saw them hold it", not held means "I deduced they don't have it"\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP Index postion
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "bool DetectiveCardEntry\&.ShouldDisplayCross (int playerIndex)"

.PP
True if this column should be displayed by the UI Includes inactive columns\&. (so empty seats are x out) and active columns that have been auto/manual crossed out\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP Postion of player
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "void DetectiveCardEntry\&.UndoManual (int playerIndex)"

.PP
Human player un-ticks the cross button\&. 
.PP
\fBParameters\fP
.RS 4
\fIplayerIndex\fP \fBPlayer\fP postion
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
