.TH "DiceController" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiceController \- Controls running the two dice, and handles the animation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRollDice\fP ()"
.br
.RI "Called when Roll button is pressed\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action< int > \fBOnRollComplete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controls running the two dice, and handles the animation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
