.TH "Dice" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dice \- Class \fR\fBDice\fP\fP represents a dice used in the game\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDice\fP (int sidesInput=6)"
.br
.RI "Creates a new instance of the \fR\fBDice\fP\fP class\&. "
.ti -1c
.RI "int \fBRoll\fP ()"
.br
.RI "Simulates a roll of the dice\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBDice\fP\fP represents a dice used in the game\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dice\&.Dice (int sidesInput = \fR6\fP)"

.PP
Creates a new instance of the \fR\fBDice\fP\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIsidesInput\fP The number of sides the dice should have\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Dice\&.Roll ()"

.PP
Simulates a roll of the dice\&. 
.PP
\fBReturns\fP
.RS 4
Returns a random integer from 1 up to the number of sides\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
