.TH "EndScreenController" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EndScreenController \- Controls the end game screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReturnToMenu\fP ()"
.br
.RI "Returns to the Main Menu scene\&. "
.in -1c
.SH "Detailed Description"
.PP 
Controls the end game screen\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
