.TH "GameController" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameController \- Class \fR\fBGameController\fP\fP controls the flow of the game, including the setup, turns and win conditions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleSuggestion\fP (int suggesterIndex, \fBSuggestion\fP suggestion)"
.br
.RI "Handles a player's suggestion\&. "
.ti -1c
.RI "void \fBHandleAccusation\fP (\fBPlayer\fP currentPlayer, \fBSuggestion\fP accusation)"
.br
.RI "Handles a player's accusation\&. "
.ti -1c
.RI "void \fBOnRollDicePressed\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetWinner\fP (\fBPlayer\fP player)"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBGetWinner\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBGameController\fP\fP controls the flow of the game, including the setup, turns and win conditions\&. 
.SH "Member Function Documentation"
.PP 
.SS "void GameController\&.HandleAccusation (\fBPlayer\fP currentPlayer, \fBSuggestion\fP accusation)"

.PP
Handles a player's accusation\&. 
.PP
\fBParameters\fP
.RS 4
\fIcurrentPlayer\fP The current player\&. 
.br
\fIaccusation\fP The \fR\fBSuggestion\fP\fP class is used to represent the Accusation\&. 
.RE
.PP

.SS "void GameController\&.HandleSuggestion (int suggesterIndex, \fBSuggestion\fP suggestion)"

.PP
Handles a player's suggestion\&. 
.PP
\fBParameters\fP
.RS 4
\fIsuggesterIndex\fP Index of the player who made the suggestion\&.
.br
\fIsuggestion\fP The \fR\fBSuggestion\fP\fP the player makes\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
