.TH "GridCell" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridCell
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridCell\fP (int x, int y, Vector3 world)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2Int \fBgridPos\fP"
.br
.ti -1c
.RI "Vector3 \fBworldPos\fP"
.br
.ti -1c
.RI "bool \fBisWalkable\fP = true"
.br
.ti -1c
.RI "bool \fBisDoor\fP = true"
.br
.ti -1c
.RI "List< \fBGridCell\fP > \fBneighbours\fP = new()"
.br
.ti -1c
.RI "\fBBoardPiece\fP \fBoccupant\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
