.TH "GridManager" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Vector3 \fBGridToWorld\fP (int x, int y)"
.br
.ti -1c
.RI "Vector2Int \fBWorldToGrid\fP (Vector3 worldPos)"
.br
.ti -1c
.RI "\fBGridCell\fP \fBGetCell\fP (int x, int y)"
.br
.ti -1c
.RI "\fBGridCell\fP \fBGetCell\fP (Vector2Int pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 24"
.br
.ti -1c
.RI "int \fBheight\fP = 25"
.br
.ti -1c
.RI "float \fBcellSize\fP = 1f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
