.TH "MenuUI" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MenuUI \- Class \fR\fBMenuUI\fP\fP represents the highest level of the menu UI, containing attributes to be used across the main menu\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetPlayerNum\fP ()"
.br
.RI "Returns the number of players to be used ingame\&. "
.ti -1c
.RI "Sprite \fBGetBackgroundSprite\fP (int spriteNum)"
.br
.RI "Returns the background sprite corresponding to the int passed in\&. "
.ti -1c
.RI "void \fBSetBackground\fP (int spriteNum)"
.br
.ti -1c
.RI "Sprite \fBGetToggleSprite\fP (int spriteNum)"
.br
.RI "Returns the toggle sprite corresponding to the int passed in\&. "
.ti -1c
.RI "void \fBSetToggleSprite\fP (int spriteNum)"
.br
.ti -1c
.RI "void \fBLoadCards\fP (int cardNum)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBToggleElement\fP (GameObject element, bool state)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBMenuUI\fP\fP represents the highest level of the menu UI, containing attributes to be used across the main menu\&. 
.SH "Member Function Documentation"
.PP 
.SS "Sprite MenuUI\&.GetBackgroundSprite (int spriteNum)"

.PP
Returns the background sprite corresponding to the int passed in\&. 
.PP
\fBParameters\fP
.RS 4
\fIspriteNum\fP An int representing the background sprite to be returned\&.
.RE
.PP
\fBReturns\fP
.RS 4
The background sprite corresponding to the int passed in\&.
.RE
.PP

.SS "int MenuUI\&.getPlayerNum ()"

.PP
Returns the number of players to be used ingame\&. 
.PP
\fBReturns\fP
.RS 4
The number of players to be used ingame\&.
.RE
.PP

.SS "Sprite MenuUI\&.GetToggleSprite (int spriteNum)"

.PP
Returns the toggle sprite corresponding to the int passed in\&. 
.PP
\fBParameters\fP
.RS 4
\fIspriteNum\fP An int representing the toggle sprite to be returned\&.
.RE
.PP
\fBReturns\fP
.RS 4
The toggle sprite corresponding to the int passed in\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
