.TH "RoomCard" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoomCard \- Class \fR\fBRoomCard\fP\fP represents a Room \fBCard\fP in the game\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoomCard\fP (string CardNameIn, Sprite spriteIn)"
.br
.RI "Instantiates a new instance of the \fR \fBRoomCard\fP\fP class\&. "
.in -1c

Public Member Functions inherited from \fBCard\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns the name of the card\&. "
.ti -1c
.RI "Sprite \fBGetSprite\fP ()"
.br
.RI "Returns the sprite for this card\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBCard\fP
.in +1c
.ti -1c
.RI "\fBCard\fP (string CardNameIn, Sprite spriteIn)"
.br
.RI "Initialises a new instance of the \fBCard\fP class\&. Set to protected as this should not be instantiated directly! "
.in -1c

Properties inherited from \fBCard\fP
.in +1c
.ti -1c
.RI "string \fBCardName\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBRoomCard\fP\fP represents a Room \fBCard\fP in the game\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RoomCard\&.RoomCard (string CardNameIn, Sprite spriteIn)"

.PP
Instantiates a new instance of the \fR \fBRoomCard\fP\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fICardNameIn\fP The name of the room\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
