.TH "RoomDefinition" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoomDefinition
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CluedoEnums\&.Room \fBroom\fP"
.br
.ti -1c
.RI "Color \fBdebugColour\fP = Color\&.cyan"
.br
.ti -1c
.RI "List< Vector2Int > \fBinteriorCells\fP = new()"
.br
.ti -1c
.RI "List< Vector2Int > \fBdoorCells\fP = new()"
.br
.ti -1c
.RI "Vector2Int \fBtokenAnchor\fP"
.br
.ti -1c
.RI "bool \fBhasSecretPassage\fP"
.br
.RI "Does this room have a secret passage to another room?

.PP
\&. "
.ti -1c
.RI "CluedoEnums\&.Room \fBsecretPassageTo\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
