.TH "Suggestion" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Suggestion \- Class \fR\fBSuggestion\fP\fP represents a suggestion/accusation made by a player\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSuggestion\fP (\fBCharacterCard\fP characterIn, \fBRoomCard\fP roomIn, \fBWeaponCard\fP weaponIn)"
.br
.RI "Creates a new instance of the \fR\fBSuggestion\fP\fP class\&. "
.ti -1c
.RI "\fBCharacterCard\fP \fBGetCharacter\fP ()"
.br
.RI "Gets the Character \fBCard\fP contained\&. "
.ti -1c
.RI "\fBWeaponCard\fP \fBGetWeapon\fP ()"
.br
.RI "Gets the \fBWeaponCard\fP contained\&. "
.ti -1c
.RI "\fBRoomCard\fP \fBGetRoom\fP ()"
.br
.RI "Gets the \fBRoomCard\fP contained\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fR\fBSuggestion\fP\fP represents a suggestion/accusation made by a player\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Suggestion\&.Suggestion (\fBCharacterCard\fP characterIn, \fBRoomCard\fP roomIn, \fBWeaponCard\fP weaponIn)"

.PP
Creates a new instance of the \fR\fBSuggestion\fP\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIcharacterIn\fP The suggested/accused character\&. 
.br
\fIroomIn\fP The suggested/accused room\&. 
.br
\fIweaponIn\fP The suggested/accused weapon\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBCharacterCard\fP Suggestion\&.GetCharacter ()"

.PP
Gets the Character \fBCard\fP contained\&. 
.PP
\fBReturns\fP
.RS 4
The \fR\fBCharacterCard\fP\fP\&.
.RE
.PP

.SS "\fBRoomCard\fP Suggestion\&.GetRoom ()"

.PP
Gets the \fBRoomCard\fP contained\&. 
.PP
\fBReturns\fP
.RS 4
The \fR\fBRoomCard\fP\fP\&.
.RE
.PP

.SS "\fBWeaponCard\fP Suggestion\&.GetWeapon ()"

.PP
Gets the \fBWeaponCard\fP contained\&. 
.PP
\fBReturns\fP
.RS 4
The \fR\fBWeaponCard\fP\fP\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
