.TH "SuspectStart" 3 "CluedoSWE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuspectStart
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CluedoEnums\&.Suspect \fBsuspect\fP"
.br
.ti -1c
.RI "Vector2Int \fBgridPosition\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CluedoSWE from the source code\&.
